### ISSUE TITLE
v3.7.0-v3.8.4 adds empty keys for "woff", "woff2", "eot", "ttf", "svg", and "jpg" files

### ISSUE THREAD

**Issue by jktravis** [ztoben/assets-webpack-plugin#103]
In upgrading from v3.6.0 to latest (3.8.4), I found the output file now includes a whole section that appears to be improperly keyed, that then has sub keys for each of the above font and file types. 

**3.6.0 and 4.0.0**
```json
{
  "logon": {
    "js": "./logon.js"
  },
  "main": {
    "js": "./main.js",
    "css": "./main.css"
  }
}
```
**3.7.0 - 3.8.4 and 3.8.4-alpha.0**
```json
{
  "logon": {
    "js": "./logon.js"
  },
  "main": {
    "js": "./main.js",
    "css": "./main.css"
  },
  "": {
    "woff": [
      "./fa2772327f55d8198301fdb8bcfc8158.woff",
      "./fee66e712a8a08eef5805a46892932ad.woff"
    ],
    "eot": [
      "./674f50d287a8c48dc19ba404d20fe713.eot",
      "./f4769f9bdb7466be65088239c12046d1.eot"
    ],
    "ttf": [
      "./b06871f281fee6b241d60582ae9369b9.ttf",
      "./e18bbf611f2a2e43afc071aa2f4e1512.ttf"
    ],
    "woff2": [
      "./af7ae505a9eed503f8b8e6982036873e.woff2",
      "./448c34a56d699c29117adc64c43affeb.woff2"
    ],
    "svg": [
      "./89889688147bd7575d6327160d64e760.svg",
      "./912ec66d7572ff821749319396470bde.svg"
    ],
    "jpg": "./4d8e58f9454c719bb731c0992bdf38db.jpg"
  }
}

```

Is this intentional? If so, how are these intended to be used? 

Also to note that v4.0.0 does not have this problem, but since it wasn't tagged as the latest or anything, I was uncertain if this was this was still under works. 

I had only noticed this because I had written code to parse this file. And the empty key causes that to break.

**Comment by ztoben** [comment]
I think `v4.0.0` was an unintentional release at some point? That behavior isn't intentional though, it should place them in the main section. I'll take a look at this.

**Comment by ztoben** [comment]
@jktravis I think that `v4.0.0` was a botched release at some point. But yes, this is intended behavior.

It was added in https://github.com/ztoben/assets-webpack-plugin/pull/65

I'd be happy to look at a PR if you want to make it toggle-able.

**Comment by jktravis** [comment]
I'd like to try to make this optional. I've never made webpack plugin before, though. I also don't see a test for this particular kind of result, so I'm unsure where to start.

**Comment by ztoben** [comment]
My recommendation for where to start would be in `index.js`. You should be able to find how options are passed there and add yours. 

Actually I think all of the changes would take place there. On line 60 you can see the blank chunk being pushed. 

I'd recommend mom linking with your other project locally and using console logs to figure out what it's doing. Nothing in your PR would really be webpack specific knowledge. Just transformation of data.

Happy to answer other questions.

**Comment by ztoben** [comment]
@jktravis, here's how I'd probably implement it:

```js
  this.options = merge({}, {
    filename: 'webpack-assets.json',
    prettyPrint: false,
    update: false,
    fullPath: true,
    manifestFirst: true,
    useCompilerPath: false,
    fileTypes: ['js', 'css'],
    includeAllFileTypes: true
  }, options)
```

```js
  var typeName = getAssetKind(options, asset)
  if (self.options.includeAllFileTypes || self.options.fileTypes.includes(typeName)) {
    var combinedPath = assetPath && assetPath.slice(-1) !== '/' ? `${assetPath}/${asset}` : assetPath + asset
  ...
```

So it would default to using all file types. When the toggle is turned off, then it would include file types from the fileTypes array provided as an option which would be defaulted to just `js` and `css`.

**Comment by ztoben** [comment]
Actually ended up just implementing it like that, should be in release `v3.9.4`.

**Comment by jktravis** [comment]
Oh! LOL Okay. Thanks!

**Comment by ztoben** [comment]
Yeah, I was in there anyway so figured might as well. New release just went out, let me know if that works for you. For your setup you should just need:

```js
  new AssetsPlugin({includeAllFileTypes: false})
```

**Comment by jktravis** [comment]
Works great! Thanks again!
