### ISSUE TITLE
Doesn't support webpack 4 entries with multiple chunks

### ISSUE THREAD

**Issue by wmertens** [ztoben/assets-webpack-plugin#108]
Example `stats.entrypoints`:
```json
{
  "app": {
    "chunks": [
      2,
      22
    ],
    "assets": [
      "2_fe9b4e17a595c7d20d6c.js",
      "2_fe9b4e17a595c7d20d6c.js.map",
      "style-9a6ae4127a5129ee48ca.css",
      "app-9a6ae4127a5129ee48ca.js",
      "style-9a6ae4127a5129ee48ca.css.map",
      "app-9a6ae4127a5129ee48ca.js.map"
    ],
    "children": {},
    "childAssets": {}
  }
}
```

This happens if you put `optimization:{splitChunks:{chunks:'all'}}` in your config.

**Comment by ztoben** [comment]
@wmertens, Could you edit your post to include your config and the expected output as well?

**Comment by ztoben** [comment]
Think this is breaking some other functionality so going to revert #109 and reopen this.

**Comment by DanieleGBX** [comment]
Have you checked how encore does this? https://github.com/symfony/webpack-encore/blob/c247131aa8ec4a4c1582fd3e862539461113402a/lib/webpack/entry-files-manifest-plugin.js

**Comment by ztoben** [comment]
@DanieleGBX, no I haven't. With all the pain this caused last time I'm not overly eager to start on it again. If you put together a PR I'd be happy to take a look.

**Comment by DanieleGBX** [comment]
I'll try to see if the folks from Encore can provide some guidance, as they seem to have figured some part of it.
