### ISSUE TITLE
webpack-assets.json Not Being Generated

### ISSUE THREAD

**Issue by FraserHamilton** [ztoben/assets-webpack-plugin#116]
Updating to 3.9.0 seems to have resulted in the webpack-assets.json file no longer being generated.

Seems to be that reverting to 3.8.4 resolves this and the file is generated without a hitch.

I'll try to investigate further after work.

**Comment by ztoben** [comment]
Looks like an issue with the path being set incorrectly. When I run it my `assets.json` file is build in my dist.

**Comment by ztoben** [comment]
Could I see your webpack config? I'm guessing you aren't setting a path so it's defaulting to the webpack output directory.

I'll wrap a flag around defaulting to '.', before choosing to use the webpack output option.

**Comment by rebolyte** [comment]
Had this same problem which broke our CI pipeline. Reverting to 3.8.4 works fine.

**Comment by ztoben** [comment]
A new flag is added in `v3.9.1` called `useCompilerPath` to fix this. I had accidentally set priority to the compiler path over the default path. If you have any issues let me know and I'll re-open this issue.

**Comment by ztoben** [comment]
@rebolyte, this should be working in the latest release.

**Comment by rebolyte** [comment]
The path issue appears to be solved in 3.9.1, but the output format has changed with the merge for 3.9.0, so we can't upgrade (at least at the moment).

The old:

```
  "Reports/default": {
    "js": "/App/Dist/Scripts/Reports/default.35764b0557.js",
    "css": "/App/Dist/Styles/Reports/default.946bf42c3d.css"
  },
  "Wizard/default": {
    "js": "/App/Dist/Scripts/Wizard/default.61c9961805.js"
  },
```

vs the new:

```
...
  "Reports/default": {
    "js": [
      "/App/Dist/Scripts/manifest.fb9c396be7.js",
      "/App/Dist/Scripts/Bundles/vendors.b2a51346c9.js",
      "/App/Dist/Scripts/commons.2352cc1fba.js",
      "/App/Dist/Scripts/Reports/default.35764b0557.js"
    ],
    "css": "/App/Dist/Styles/Reports/default.946bf42c3d.css"
  },
  "Wizard/default": {
    "js": [
      "/App/Dist/Scripts/manifest.fb9c396be7.js",
      "/App/Dist/Scripts/Bundles/vendors.b2a51346c9.js",
      "/App/Dist/Scripts/commons.2352cc1fba.js",
      "/App/Dist/Scripts/Wizard/default.61c9961805.js"
    ]
  },
...
```
I would have expected a major version bump for breaking changes like this.

EDIT: I see this has been brought up in #118 .

**Comment by ztoben** [comment]
Thanks for the feedback, this wasn't intentional and I'm looking into it.

**Comment by ztoben** [comment]
@rebolyte, that should be fixed in `v3.9.2`. Let me know otherwise, thanks!

**Comment by Trainmaster** [comment]
I have the same issue that the assets file isn't generated. Using the `useCompilerPath` doesn't change anything. The webpack option `output.path` isn't set and it's working with `3.8.4`.

**Comment by ztoben** [comment]
@Trainmaster, oops forgot to resolve the path when using `useCompilerPath`. Should be fixed in `v3.9.3`.

**Comment by Trainmaster** [comment]
@ztoben It still doesn't work with `3.9.3`, regardless of using `new AssetsPlugin({useCompilerPath: true})` or `new AssetsPlugin()`. And I don't see any error message.

**Comment by ztoben** [comment]
`useCompilerPath` being set to true would make it generate to wherever you have your `output.path` set. So if it's not set it makes sense you aren't seeing it. 

Not sure why it wouldn't be generating in the base path when no options are provided though. Didn't you confirm that it worked for you in `3.8.4-alpha.1`?

**Comment by ztoben** [comment]
@Trainmaster, since yours seems to be a different issue I've opened #124. Feel free to add any more context there.
