### ISSUE TITLE
Backward incompatible change on the generated file in 3.9.0-3.9.1

### ISSUE THREAD

**Issue by loispostula** [ztoben/assets-webpack-plugin#118]
I am using webpack 3.5, and was used to have a assets.json that look like this:
```
{
  asset_1: {
    js: "asset_1-hash.js",
    css: "asset_1-hash.css"
  },
   ...
  commons: {
    js: "commons-hash.js",
    css: "commons-hash.css",
  },
}
```
And now it looks like this
```
{
  asset_1: {
  js: [
    "commons-hash.js",
    "asset_1-hash.js"
  ],
  css: [
    "commons-hash.css",
    "asset_1-hash.css"
  ]
  },
}
```
Which is kind of a huge incompatible change. And I don't see any info about this, nor warnings.

**Comment by ztoben** [comment]
I'm not sure why it's grouping them like that, could I see your webpack config?

~~As far as the array of assets goes, this was a change in `v3.6.3`. If you only have one asset it should still show up as a string, but if there are multiple then it will place them in an array. I can add this to the documentation, and can probably add a flag around this in a corner case like yours where you only want the first asset.~~

Edit: scratch that this is definitely a bug. Could anyone having the issue share their webpack config? Thanks!

**Comment by davidtheclark** [comment]
I'm having the same problem, and can confirm that 3.8.4 works the same as before but 3.9.0+ breaks the output. So I'd definitely consider this a bug, not an enhancement.

**Comment by sballesteros** [comment]
same here, downgrading to 3.8.4 fixes it.

**Comment by ztoben** [comment]
Yeah, sorry definitely seems to be a bug. Could I get some of your webpack configs so I can try to replicate locally?

**Comment by davidtheclark** [comment]
@ztoben: Here's a snapshot of a Webpack config that illustrated the problem: https://github.com/mapbox/batfish/blob/503064de33ebffa407bbdf5d20e44a8c71964ccd/test/__snapshots__/create-webpack-config-client.test.js.snap#L109-L231

**Comment by ztoben** [comment]
I think it was caused by #109. Going to revert that and publish a new release.

**Comment by davidtheclark** [comment]
Thanks @ztoben 🥇

**Comment by wmertens** [comment]
Yes due to #109 for sure. In Webpack 4, you can let it split the entry js as it sees fit, and that automatically creates a commons chunk. Easy to use, just map across the js array, creating script tags.

I think the new behavior will have to be behind a flag. I'm not sure why the named commons chunk isn't showing up either, I would expect it to be listed too.

**Comment by loispostula** [comment]
Thanks @ztoben, do you still need a config?

**Comment by ztoben** [comment]
@loispostula, for use in testing this eventually I wouldn't mind it. But for now I think this should be fixed in `v3.9.2`. Let me know if any of you still have problems otherwise I'll close this out. Thanks!

**Comment by ztoben** [comment]
Just confirming, @davidtheclark this is fixed for you now?

**Comment by davidtheclark** [comment]
I'm not planning to update until I switch some systems onto Webpack 4. At that point I'll be able to let you know if it's still a problem.

**Comment by ztoben** [comment]
@sballesteros, what about you?

**Comment by ejuo** [comment]
Hello.
Could you help me?
The plugin assets-webpack-plugin has stopped working since version 3.9. The file is simply not created, errors are not output. I attach the configuration file.

3.8.4 works very well.
[apps.txt](https://github.com/ztoben/assets-webpack-plugin/files/2272955/apps.txt)

**Comment by loispostula** [comment]
@ztoben With 3.9.2 the situation is back to normal, Here is a redacted version of my webpack config:
```
const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const CircularDependencyPlugin = require('circular-dependency-plugin');
const AssetsPlugin = require('assets-webpack-plugin');


module.exports = {
    context: __dirname,
    entry: {
        entry_1: ['babel-polyfill', './frontend/entry_1/static/js/index.js'],
        entry_2: ['babel-polyfill', './frontend/entry_2/static/js/index.js'],
    },
    output: {
        path: path.join(__dirname, './bundles'),
        filename: '[name]-[hash].js',
        chunkFilename: '[id].js',
        libraryTarget: 'var',
        library: 'EntryPoint_[name]',
        sourceMapFilename: '[file].map',
    },
    plugins: [
        new AssetsPlugin({
            path: path.join(__dirname, './bundles'),
            useCompilerPath: false,
        }),
        new webpack.ExtendedAPIPlugin(),
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery',
            Cookies: 'js-cookie',
            _: 'underscore',
            i18n: 'i18next',
        }),
        new CircularDependencyPlugin({
            exclude: /node_modules/,
            failOnError: true,
        }),
    ],
    module: {
        rules: [{
            test: /\.css$/,
            loader: ExtractTextPlugin.extract({
                fallback: 'style-loader',
                use: 'css-loader',
            }),
        }, {
            test: /\.scss$/,
            loader: ExtractTextPlugin.extract({
                use: [{
                    loader: 'css-loader',
                    options: {
                        sourceMap: true,
                    },
                }, {
                    loader: 'sass-loader',
                    options: {
                        sourceMap: true,
                    },
                }],
                fallback: 'style-loader',
            }),
        }, {
            test: /\.js$/,
            use: 'babel-loader',
            exclude: /node_modules/,
        }, {
            test: /\.png$/,
            use: {
                loader: 'url-loader',
                options: {
                    limit: 100000,
                },
            },
        }, {
            test: /\.jpg$/,
            use: ['file-loader'],
        }, {
            test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/,
            use: {
                loader: 'url-loader',
                options: {
                    limit: 100000,
                    mimetype: 'application/font-woff',
                },
            },
        }, {
            test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
            use: {
                loader: 'url-loader',
                options: {
                    limit: 100000,
                    mimetype: 'octet-stream',
                },
            },
        }, {
            test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
            use: 'file-loader',
        },
        {
            test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
            use: {
                loader: 'url-loader',
                options: {
                    limit: 100000,
                    mimetype: 'image/svg+xml',
                },
            },
        }],
    },
    stats: {
        children: false,
    },
};
```

**Comment by ztoben** [comment]
@ejuo, could you open a new issue. I think that yours is related to using gulp streams. @trainmaster is having a similar issue.
