### ISSUE TITLE
Assets doesn't generated in webpack-dev-server

### ISSUE THREAD

**Issue by horprogs** [ztoben/assets-webpack-plugin#123]
For example, I use boilerplate react+webpack etc. (https://github.com/esausilva/react-starter-boilerplate-hmr).
Setup assets-webpack-plugin according docs.
When I build project, assets file generate, ok. But if I run project locally with webpack-dev-server assets not generated. Is it normal? Or I doing something wrong?

**Comment by ztoben** [comment]
It's now generated in memory and not written to disk in this scenario. I'll add some documentation around it.

**Comment by alkismavridis** [comment]
I was also affected.
We were importing the generated file into an other js file.
The file was not generated, so the whole app crashes.
I had to downgrade.

Any advice for my case?

**Comment by horprogs** [comment]
I found, that version `assets-webpack-plugin@3.8.0` works fine (webpack-dev-server generate assets file). But the latest version of `assets-webpack-plugin` doesn't write assets to disk.. Why?
Also I found similar issue https://github.com/ztoben/assets-webpack-plugin/issues/93

**Comment by ztoben** [comment]
@horprogs, #93 isn't related to this. Like I already said it's now being generated in memory like other webpack plugins. I plan on adding this to the docs, and possibly adding a flag/option for cases like yours where you want it written to disk.

**Comment by TheDutchCoder** [comment]
It would be good to do a major release for this, instead of a minor.

This is a breaking change and breaks our workflow (it took a long time to figure out why).

Edit: to clarify: it looks like you're trying to stay in line with the major webpack versions (for good reason), so my suggestion is to use their major versions in your semver.

E.g. this plugin should now be in 4.x.y if it aligns with webpack v4.

**Comment by ztoben** [comment]
@TheDutchCoder, yeah that's a good point. I'll see what I can do about getting this back to the old functionality for another minor release before pushing out a major release. Sorry for any headaches.

**Comment by TheDutchCoder** [comment]
@ztoben no problem, it's all part of OOS development ;) Thanks for taking the time to reply and keeping us in mind!

**Comment by ztoben** [comment]
@TheDutchCoder are you in a situation where you could pull down master and run with npm link? I have some changes that are working for me locally, but want to check that they work with other setups too before I do a release.

**Comment by TheDutchCoder** [comment]
@ztoben I'm actually in the middle of writing some integration tests, so I won't be able to do that right now, but I might have some time at the end of the day to do a test for you.

Maybe someone else can help out quicker?

**Comment by ztoben** [comment]
@TheDutchCoder not a problem. I'll work on it more later and let you know. Thanks!

**Comment by ztoben** [comment]
@TheDutchCoder if you get a chance, I just pushed some code that adds an option called `keepInMemory`. By default I now have it set to false, so it should be back to generating the file when running `webpack-dev-server`. If set to true then it will only generate in memory.

Let me know if it works for you. Thanks!

**Comment by TheDutchCoder** [comment]
@ztoben Yeah I'll give it a shot right now.

Hang tight!

Update: it throws an error for me: `Error: Cannot find module './lib/getAssetKind'`
Actually, there's no lib folder at all. Wondering if I did something wrong

**Comment by ztoben** [comment]
Steps to link:

1. In the `assets-webpack-plugin` directory run `npm i && npm run build && npm link`
2. In the other project run `npm link assets-webpack-plugin`

Now you should be able to your other project pointing to your local version of `assets-webpack-plugin`.

If you're still having issues, maybe @horprogs, or @alkismavridis could help test it.

**Comment by TheDutchCoder** [comment]
I'm afraid I'm not sure how that works.

Do I pull master in the node_modules/assets-webpack-plugin folder and then use `npm link` and `npm run build`?

The npm docs are a bit vague on how this works ;)

**Comment by ztoben** [comment]
You would just pull down the master branch of this project anywhere on your computer. Then go to that directory and follow the steps I outlined above for step 1. Then go to your project that is using `assets-webpack-plugin` and follow step 2.

If that makes sense? Sorry if I'm not explaining clearly.

**Comment by TheDutchCoder** [comment]
Okay give me a minute ;)

**Comment by TheDutchCoder** [comment]
@ztoben Yup that works fine for me!

**Comment by ztoben** [comment]
Okay, I'll get a new version pushed out here soon.

**Comment by ztoben** [comment]
This should be fixed in `v3.9.5`. Let me know otherwise, thanks!

**Comment by TheDutchCoder** [comment]
Just installed it and looks good for me again!

Thanks for reacting so quickly, I appreciate it!

**Comment by ztoben** [comment]
Absolutely, this was just an oversight on my part. Thanks for bringing it up.

**Comment by horprogs** [comment]
Yes, works fine! Thank you!!

**Comment by alkismavridis** [comment]
@ztoben sorry that I did not respond, I just read the messages.
I can confirm that v3.9.5 works great. Thanks a lot!
