### ISSUE TITLE
Build directory compiled prior to assets.json creates disconnect

### ISSUE THREAD

**Issue by mwelche** [ztoben/assets-webpack-plugin#14]
i'm attempting to use this plugin in my React/Fluxible project, however because the assets.json file is created after the bundle has already been compiled, the included assets.json file is not found during the build. If i redo the build process a second time without making changes it works. Not sure if this is an issue with the plugin or my configuration. If assets.json is required before the build process, but can't be built until the hash has been created, how's the flow supposed to go?

```
var config = {
  resolve: {
    extensions: ['', '.js']
  },
  entry: './app/client.js',
  output: {
    path: './build/js',
    publicPath: '/public/js/',
    filename: '[name]-[hash].js'
  },
  module: {
    loaders: [
      { test: /\.js$/, exclude: /node_modules/, loaders: ['babel'] },
      { test: /\.json$/, loader: 'json-loader'},
      { test: /\.css$/, loader: ExtractTextPlugin.extract('style', 'css!autoprefixer!rework')},
      { test: /\.(jpg)$/, loader: 'file-loader' },
      { test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000' }
    ]
  },
  plugins: [
    new ExtractTextPlugin('app-[hash].css'),
    new AssetsPlugin({
      path: path.join(__dirname, 'app', 'configs'),
      filename: 'assets.json'
    })
  ],
  rework: {
    use: [
      at2x(),
      inherit(),
      reworkNPM(),
      media(),
      parent,
      vars({})
    ]
  },
  stats: {
    colors: true
  },
  devtool: 'source-map',
  watch: true,
  keepalive: true
};
```

**Comment by sporto** [comment]
The assets json file has to be generated after the webpack build is done as it needs the stats generated by webpack. How are you trying to use this assets file?

Usually you would run the webpack build and then run something else that will use the assets json. Maybe a gulp task.

**Comment by jimthedev** [comment]
Make sure you're not using `require();` to load the json file. If you do this then it will get cached. You should use fs.readFile or fs.readFileSync.
