### ISSUE TITLE
empty key for assets folder

### ISSUE THREAD

**Issue by MarcoGomesr** [ztoben/assets-webpack-plugin#149]
I just install and setup my config webpack following the steps from the `readme.md` and   I'm geting an empty key

_config_

**webpack.base.conf.js**

```
entry: {
   app: ['./src/main.js'],
},

 .........


plugins: [
    new AssetsPlugin({
        filename: 'manifest.json',
        path: resolve('src/assets'),
        includeAllFileTypes: false,
        fileTypes: ['js', 'jpg', 'woff', 'woff2', 'otf'],
        manifestFirst: true,
        prettyPrint: true,
    })
```
_output_

**manifest.json**
```

{
  "app": {
    "js": "/app.js"
  },

  "": {
    "jpg": [
      "/static/img/24_tablet.1142952.jpg",
      "/static/img/10_desktop.0a66f1a.jpg",
      "/static/img/10_mobile.e16be9f.jpg"
     ],
   }
}
```

**version**

_package.json_
```

 "dependencies": {
    "assets-webpack-plugin": "^3.9.7",
    "webpack": "^3.6.0",
    "vue": "^2.5.2",
 }
```

**Comment by ztoben** [comment]
https://github.com/ztoben/assets-webpack-plugin/pull/65
https://github.com/ztoben/assets-webpack-plugin/issues/103

**Comment by ztoben** [comment]
Let me know if you need help with this. Basically, those assets aren't in a chunk so we just add them as an empty keyed object. If you don't want them you can set the option like this:

```js
  new AssetsPlugin({includeAllFileTypes: false})
```

**Comment by TheDutchCoder** [comment]
Would it be possible to have an option to give those a custom key?
This would make it easier to traverse the JSON and select those assets.

It could possibly end up conflicting with a generated key of course, but maybe something like `undefined` would fit?

**Comment by ztoben** [comment]
@TheDutchCoder, probably a pretty simple PR if you want to give it a try. Or I can get around to it eventually. Pretty busy with other work at the moment so it could be a while.
