### ISSUE TITLE
Prototype pollution vulnerability affecting lodash.merge package

### ISSUE THREAD

**Issue by dr3** [ztoben/assets-webpack-plugin#167]
**Describe the bug**
This package uses lodash merge `^4.6.1` and snyk has reported a vulnerability https://snyk.io/vuln/SNYK-JS-LODASHMERGE-173732

**To Reproduce**
1. Run the synk cli tool on this package

**Expected behavior**
Vulnerabilities are avoided where possible, please consider upgrading to lodash.merge in version 4.17.11 of lodash itself.

**Comment by ztoben** [comment]
@dr3 this should be fixed in `v3.9.8`. Thanks for the heads up!

**Comment by dr3** [comment]
Ah fantastic, cheers :D @ztoben
