### ISSUE TITLE
Can this works with other files than entries?

### ISSUE THREAD

**Issue by schovi** [ztoben/assets-webpack-plugin#18]
Hi,

It is longtime, when i started to fight with simple idea where i want to export all relevant files into hash like your package does. Not just main javascripts, but stylesheets and all other assets (images, fonts etc...) required by webpack.
Stats result is really huge and contains all files which are required in my app and are hard to works with.

Maybe you can do something like that with you module, but you just skip that because you dont need it, or have major know-how about stat file and how this can be dome?

Thanks

**Comment by sporto** [comment]
hi @schovi  at the moment is just JS and JS source maps. I will need to investigate how much work is involved.

**Comment by schovi** [comment]
@sporto I made it works in my project

I had to improve your module function `ExtractAssets`

```javascript
function ExtractAssets(modules, requestShortener, publicPath) {
  var emitted = true;
  var assets = modules
    .map(m => {
      let name = m.readableIdentifier(requestShortener)

      if(name.slice(0,2) != "./")
        return

      name = name.slice(2, name.length)

      const assets = Object.keys(m.assets || {})

      let asset;

      if (assets.length) {
        asset = assets[0];

      } else if(m._source) {
        const source = m._source.source()
        asset = source.slice(18, source.length - 1)
      }

      if(!asset)
        return

      return {
        name: name,
        asset: asset
      };

    }).filter(m => {
      return m !== undefined;
    }).reduce((acc, m) => {
        acc[m.name] = url.resolve(publicPath, m.asset);
      return acc;
    }, {});

  return [emitted, assets];
}
```

As you can see there is some stupid condition to filter out assets i dont want. Otherwise stats.json is really huge and parsing takes some.

Then in my server initializer I have following

```javascript
import addModulePath from 'app-module-path';

////// Fix Webpack assets
// Add assets load path
const assetsPath = path.join(__dirname, 'assets/')

addModulePath.addPath(assetsPath);

// To ignore webpack custom loaders on server.
['css', 'less', 'sass', 'styl'].forEach((ext) => {
  require.extensions['.' + ext] = () => {}
})

// Override assets requiring
let assetCache;

const getAssets = () => {
  if(assetCache)
    return assetCache

  console.log("Getting assets from webpack 'build/assets.json'")
  assetCache = JSON.parse(fs.readFileSync(path.join(__dirname, 'build/assets.json')))

  return assetCache
}

// Overiding requiring of assets
['jpg', 'jpeg', 'png', 'gif', ...].forEach((ext) => {
  require.extensions['.' + ext] = (require, path) => {
    const file = path.replace(assetsPath, "")
    require.exports = getAssets().assets[file]
  }
})
```

Now I can load assets if they are just url or base64 on server side. It is ugly, but it is mine and it works :)

**Comment by jeffutter** [comment]
I would really like this too. I am using the image loader and file loader to dump some files to my public/ dir. It would be nice if I could get the images into the asset.json as well.

**Comment by sporto** [comment]
With my current priorities it is very unlikely that I will work on this myself but I will be very happy to take a PR for this.

**Comment by tonytonyjan** [comment]
I have the same problem, and I'm using this solution:

``` js
plugins: [
  function() {
    this.plugin('done', function(stats) {
      fs.writeFileSync(__dirname + '/stats.json', JSON.stringify(stats.toJson()))
    })
  }
]
```
