### ISSUE TITLE
Question: Callback JSON method

### ISSUE THREAD

**Issue by thurfir** [ztoben/assets-webpack-plugin#201]
Hello, is there a way to alter the JSON output before it is written to the output directory?

In my specific case, I would like to add a root node to the JSON, eg: 
```
{
    "MyAssets": {
        "entry1": {
            "js": "entry1.js"
        },
        "entry2": {
            "js": "entry2.js"
        }
    }
}
```
so it can be read and watched like a classic appsettings.json .NET Core configuration file.

**Comment by ztoben** [comment]
You could accomplish this with the `processOutput` option.

Something like this I think (not tested):
```js
new AssetsPlugin({
  processOutput: function (assets) {
    return JSON.stringify({MyAssets: assets}, null, 2)
  }
})
```

**Comment by thurfir** [comment]
It works perfectly, thank you 👍
