### ISSUE TITLE
Add a new option to include assets that aren't in any chunk

### ISSUE THREAD

**Issue by martin-eq** [ztoben/assets-webpack-plugin#204]
**Is your feature request related to a problem? Please describe.**
In our project, we are using the `entrypoints` option set to true to organize el assets output by entry points so we can load the proper assets for each page. We would like to preload the font assets, which aren't in any chunk due to being imported in scss files. Those assets are part of the "unnamed chunk" which is included in the assets file when `entrypoints` is false.

**Describe the solution you'd like**
We would like to include a new option called `includeFilesWithoutChunk` which is false by default and when set to true, the assets from the "unnamed chunk" would get included in the assets file under a "unnamed key" in the json output.

**Describe alternatives you've considered**
We haven't think of other alternatives for solving this problem. Suggestions are welcome.

**Additional context**
We are testing this change on a fork that we included in our project. The code change diff looks like this:
<img width="1440" alt="Screen Shot 2019-11-21 at 14 46 54" src="https://user-images.githubusercontent.com/2282190/69362731-dacc1d80-0c6d-11ea-93e8-46d7875f1eed.png">
If this solution is accepted, I can create a PR with this code to this repo.

Thanks!

**Comment by catalinux** [comment]
How did you solve this?

**Comment by ztoben** [comment]
Sorry, must have missed this one. That seems like a reasonable solution, happy to take a look at any PRs @martin-eq!
