### ISSUE TITLE
Update dependency mkdirp to v1

### ISSUE THREAD

**Issue by hectorbenitez** [ztoben/assets-webpack-plugin#226]
**Describe the bug**
npm install assets-webpack-plugin --save-dev
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

**To Reproduce**
1. npm install assets-webpack-plugin --save-dev

**Expected behavior**
Show no warns

**Webpack Config**
The webpack configuration you are using when seeing the bug.

**Desktop (please complete the following information):**
 - OS: OSX
 - Node version: 12 
 - Plugin version: 3.9.12

**Comment by ztoben** [comment]
Should be fixed in the upcoming release.
