### ISSUE TITLE
AssetsPlugin + .netcore appsettings

### ISSUE THREAD

**Issue by thurfir** [ztoben/assets-webpack-plugin#231]
Hi,

I use the AssetsPlugin to export my assets into a .net core appsettings.json configuration file. This file is then watched by the .net core framework and used to import the assets into my pages.

This process works most of the time, however if I refresh a page too soon after updating an asset (js or css) , the .net core crashes saying it doesn't understand what's inside the appsettings.json file.
My guess is the .net core framework reads the file before AssetsPlugin has finished writing.

Here is my configuration:

```
const assetsPlugin = new AssetsPlugin({
    entrypoints: true,
    path: distFolder,
    update: true,
    filename: 'appsettings_webpack.json',
    processOutput: (assets) => JSON.stringify({ PagesAssets: assets })
});
```

Do you have a suggestion about making these two plays nice?

**Comment by ztoben** [comment]
Not entirely my area of expertise, but I think you could potentially use the WebpackTag helper?

https://github.com/ztoben/assets-webpack-plugin#using-this-with-aspnet-core

@Daniel15 may be able to assist you.

**Comment by Daniel15** [comment]
>  the .net core crashes saying it doesn't understand what's inside the appsettings.json file.

Do you have the exact error message you're seeing?

WebpackTag supports hitting the Webpack dev server rather than reading the file from disk, so that's another option.

**Comment by thurfir** [comment]
Hi @ztoben, @Daniel15, I'm mostly getting "ConfigurationErrorsException: 'The configuration section PagesAssets is not configured properly'", and from time to time a "max JSON depth exceeded" exception.

Just to clarify I'm using the net core appsettings.json parser, not WebpackTag. While it seems convenient, I'm planning to use the Assets for purposes besides JS/CSS rendering so I wanted a more flexible approach. I see you built your own parser in WebpackTag, was it to avoid the same issue?

**Comment by ztoben** [comment]
Neither of those errors sound like they're coming from this plugin unfortunately.

**Comment by thurfir** [comment]
Yes these errors are .net exceptions of course, but they occur when the parser fails to read the plugin output.

It occurs only for a short while after a JS/CSS modification:
1. I trigger a page load, the page loads properly.
2. I update a css/js, and reload, the page crashes (errors above).
3. I wait a few seconds then reload, the page loads properly.

From the error messages, my guess is the plugin writes to its output in chunks without locking the file (read lock) in-between writes. The .net parser sees the file as readable, but stumbles on files like

`{ entry1: "...", entry2: "", ent [content truncated]`

which is not a valid JSON, triggering a crash.

**Comment by ztoben** [comment]
Yeah, I would assume it's definitely an error of that variety. Unfortunately I'm not sure the best way to approach your issue.

**Comment by Daniel15** [comment]
@ztoben I haven't looked at the code for this plugin yet, but does it write the entire file atomically, or does it write it a chunk at a time? I imagine various tools that watch the file system may encounter issues if the writes are not atomic and they read the file as soon as one write completes, without waiting for further writes. Alternatively I wonder if it could write to a temp file, then delete the destination file and move the temp file into its place (or have that as an option)

**Comment by ztoben** [comment]
@Daniel15 I don't think anything fancy is done. This should be where most of the file writing is done:

https://github.com/ztoben/assets-webpack-plugin/blob/55dd5e5e9b5884043074e6f5425710ee195e91fe/lib/output/createOutputWriter.js#L62

**Comment by thurfir** [comment]
hi @ztoben , I checked the plugin code, can you explain to me what is the point of the createQueuedWriter module? Is afterEmit called multiple times? I apologize if this is trivial, my knowledge regarding webpack and javascript I/O is rather limited.

**Comment by ztoben** [comment]
@thurfir the queued writer deals with multi-compiler mode. Each compilation is added to the queue and written to the output. I'm not entirely sure about `afterEmit`, but I think it's called after assets are written to the output directory. So it would probably be called multiple times in the case of multi-compiler mode.

**Comment by thurfir** [comment]
Thank you @ztoben . In my specific case I don't think I am in multi-compiler mode: I use a single webpack configuration (one single module.exports object for the webpack.config.js file).

I also added a console.log in the _processOutput_ plugin option for debugging, the message appears only once after each modification even when multiple assets are impacted.

Maybe a file locking library like https://www.npmjs.com/package/proper-lockfile would help?
