### ISSUE TITLE
ERROR in [AssetsWebpackPlugin] Could not create output folder G:\WebStormWS\WebProTpl\dist\devServer\others

### ISSUE THREAD

**Issue by LP1994** [ztoben/assets-webpack-plugin#234]
assets-webpack-plugin: v5.0.0
node.js: v14.4.0
npm: v6.14.5
webpack: v4.43.0
webpack-dev-server: v3.11.0
Windows 10 professional edition 1902 18363.900

Describe the bug:
1、
ERROR in [AssetsWebpackPlugin] Could not create output folder G:\WebStormWS\WebProTpl\dist\devServer\others

To Reproduce:
1、The configuration of "webpack-dev-server" is:
...
writeToDisk: false,
......
![image](https://user-images.githubusercontent.com/12012671/84559976-06316980-ad72-11ea-8723-b3bfb0096e01.png)
2、The configuration of "assets-webpack-plugin" is:
......
useCompilerPath: false,
keepInMemory: true,
path: path.resolve( __dirname, `./dist/devServer/others/` ),
......
![image](https://user-images.githubusercontent.com/12012671/84559979-0c274a80-ad72-11ea-932b-6e0633664a4b.png)
![Uploading image.png…]()

Expected behavior：
Compilation successful!!!

PS:
However, "assets-webback-plugin v3.9.12" will not report the above mentioned errors.It can be compiled and run successfully.

**Comment by ztoben** [comment]
Okay, so you have writeToDisk off and it looks like it's still trying to write to a directory. Is that accurate?

**Comment by LP1994** [comment]
> 好的，您已经关闭了writeToDisk，并且看起来它仍在尝试写入目录。准确吗？

Yes,I'm sure.

**Comment by LP1994** [comment]
> Okay, so you have writeToDisk off and it looks like it's still trying to write to a directory. Is that accurate?

Yes,I'm sure.
But!!!
"assets-webpack-plugin": "^3.9.12"!!!
There will be no bug mentioned above!!!

**Comment by ztoben** [comment]
Okay, I see the issue. The `keepInMemory` option was broken when we updated mkdirp. I'll get a fix out soon here.

**Comment by ztoben** [comment]
@LP1994 Please verify that `5.0.1` works for you, but this should be fixed now. Thanks for the report!

**Comment by LP1994** [comment]
> @LP1994 Please verify that `5.0.1` works for you, but this should be fixed now. Thanks for the report!

Hello.It's a mistake.
![image](https://user-images.githubusercontent.com/12012671/84726872-67e71300-afc0-11ea-8156-a1b93738d436.png)

**Comment by ztoben** [comment]
@LP1994 Ah, I see what I did wrong. Can you try v5.0.2?

**Comment by LP1994** [comment]
OK
---原始邮件---
发件人:&quot;Zach Toben&quot;<notifications@github.com&gt;
发送时间:2020年6月16日 星期二 下午8:47
收件人:&quot;ztoben/assets-webpack-plugin&quot;<assets-webpack-plugin@noreply.github.com&gt;
抄送:&quot;林沐风&quot;<1227839175@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;
主题:Re: [ztoben/assets-webpack-plugin] ERROR in [AssetsWebpackPlugin] Could not create output folder G:\WebStormWS\WebProTpl\dist\devServer\others (#234)



@LP1994Ah,&nbsp;I&nbsp;see&nbsp;what&nbsp;I&nbsp;did&nbsp;wrong.&nbsp;Can&nbsp;you&nbsp;try&nbsp;v5.0.2?

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;were&nbsp;mentioned.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by LP1994** [comment]
I &#39;ll try 5.0.2. If I succeed, I&#39;ll let you know. Thank you for your update.
---原始邮件---
发件人:&quot;Zach Toben&quot;<notifications@github.com&gt;
发送时间:2020年6月16日 星期二 下午8:47
收件人:&quot;ztoben/assets-webpack-plugin&quot;<assets-webpack-plugin@noreply.github.com&gt;
抄送:&quot;林沐风&quot;<1227839175@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;
主题:Re: [ztoben/assets-webpack-plugin] ERROR in [AssetsWebpackPlugin] Could not create output folder G:\WebStormWS\WebProTpl\dist\devServer\others (#234)



@LP1994Ah,&nbsp;I&nbsp;see&nbsp;what&nbsp;I&nbsp;did&nbsp;wrong.&nbsp;Can&nbsp;you&nbsp;try&nbsp;v5.0.2?

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;were&nbsp;mentioned.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by LP1994** [comment]
> @LP1994 Ah, I see what I did wrong. Can you try v5.0.2?

OK, I'll try the latest version of 5.0.2. If it succeeds, I'll let you know. Thank you for your prompt reply.

**Comment by LP1994** [comment]
> @LP1994 Ah, I see what I did wrong. Can you try v5.0.2?

Hello, the latest version has been compiled successfully. Thank you for your timely feedback.
