### ISSUE TITLE
Relaxed versions?

### ISSUE THREAD

**Issue by daveisfera** [ztoben/assets-webpack-plugin#240]
**Is your feature request related to a problem? Please describe.**
Specific versions are used in package.json and causes multiple versions to be installed unnecessarily

**Describe the solution you'd like**
Use `^` to allow flexibility in versions to minimize packages installed

**Describe alternatives you've considered**
Use `~` to allow at least some flexibility

**Comment by ztoben** [comment]
This should be resolved in the `5.1.0` release. Let me know if you have any other concerns. Thanks!
