### ISSUE TITLE
Concurrency issue

### ISSUE THREAD

**Issue by jogelin** [ztoben/assets-webpack-plugin#241]
**Describe the bug**
I am using webpack-parallel to run multiple webpack build in the same time. Each webpack build are updating a json file with the name of the output by using the `AssetsPlugin` and `processOutput` and `update` method.

The issue is that sometimes, the generation of the assets file is overwriting another modification because the `assets` parameter provided in the `processOutput` doesn't contain the latest assets.

**To Reproduce**
```
new AssetsPlugin({
        entrypoints: true,
        update: true,
        filename: 'importmap.json',
        path: path.resolve(`./App/build/single-spa`),
        processOutput: (assets) => {
          return JSON.stringify(assets);
        },
      }),
```

1. Build of Webpackconfig_ONE and Webpackconfig_TWO starts
2. Webpackconfig_ONE calls `processOutput` with only Webpackconfig_ONE assets because not assets in the file yet
3. Webpackconfig_TWO calls `processOutput` with only Webpackconfig_TWO assets because not assets in the file yet
4. Webpackconfig_ONE generate the assets file `importmap.json` with only the assets of Webpackconfig_ONE
5. Webpackconfig_TWO overwrete the assets file `importmap.json` with only the assets of Webpackconfig_TWO

**Expected behavior**

I expect that when the file is generated by using the update mode, a check is done to be sure that the file wasn't modified since the read used to provide the assets parameter of the `processOutput` function. In this case, I would read again the file and call again the function with the latest value

**Comment by ztoben** [comment]
@jogelin Just to confirm, you're already following the directions [here](https://github.com/ztoben/assets-webpack-plugin#using-in-multi-compiler-mode)?
