### ISSUE TITLE
"auto/" prefixed when fullPath is true in webpack-dev-server and webpack 5.0.0-rc.4

### ISSUE THREAD

**Issue by SPWizard01** [ztoben/assets-webpack-plugin#269]
**Describe the bug**
having simple configuration produces json file that will have "auto/" prefixed for entrypoints.

**To Reproduce**

```
    new AssetsPlugin({
      path: resolve(__dirname, "./dist"),
      fullPath: true, //default
      entrypoints: true,
      filename: "webpack.assets",
      keepInMemory: false,
    })
```
run webpack-dev-server, observe the result of json file:
```
{"someapp":{"js":["auto/js/runtime.js?f23c9627a06ec2afb8f0","auto/js/app.js?95ae18e01b0b1cf8607a"]}}
```

change fullPath to false and observe that "auto/" part is removed.

**Expected behavior**
Unclear what should be produced with fullPath set to true, however in webpack 4 having this default (true) produced the desired results "auto/" was not included.

**Webpack Config**
webpack config
```
{
  entry: {
    someapp: resolve(__dirname, "./src/app.ts"),
  },

  output: {
    path: resolve(__dirname, "dist"),
    filename: "js/[name].js?[contenthash]",
    chunkFilename: "js/[name].js?[contenthash]",
  },
}
```
dev server
```
  headers: {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "*",
  },
  hot: true,
  watchOptions: {
    poll: true,
  },
  allowedHosts: [".mylocal.net"],
  contentBase: resolve(__dirname, "dist"),
  publicPath: "/",
  port: 56789,
}
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node version: v12.18.0
 - Plugin version: 5.1.2

**Additional context**
N/A

**Comment by ztoben** [comment]
@SPWizard01 Could you try the `6.0.0-alpha.2` release?

You'll need to set the configuration option `removeFullPathAutoPrefix` to true.

**Comment by SPWizard01** [comment]
yep it works, however its missing typing def. so i had to
```
    new AssetsPlugin({
      path: resolve(__dirname, "./dist"),
      removeFullPathAutoPrefix: true,
      // fullPath: false,
      entrypoints: true,
      filename: "webpack.assets",
      keepInMemory: false,
    } as any),
```
because i am using typescript
