### ISSUE TITLE
Unnecessary output caused by console.log()

### ISSUE THREAD

**Issue by Trainmaster** [ztoben/assets-webpack-plugin#279]
**Describe the bug**
A `console.log()` statement causes some unnecessary output. The output on CLI looks like:

```
manifest_cd63299e94811e06e990.js
vendors-node_modules_lodash__MapCache_js-node_modules_lodash_isArray_js-node_modules_lodash_i-1f8728_a207d4d09b5f5b47eb8e.js
vendors-node_modules_jquery_dist_jquery-exposed_js_711acbed7d10745c820d.js
// etc.
```

**To Reproduce**
1. Build any project with the latest version.

**Expected behavior**
No output.

**Webpack Config**
Not relevant.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1
 - Node version: 12.18.4
 - Plugin version: 6.0.1

**Comment by ztoben** [comment]
Fixed in `6.0.2`, thank you!
