### ISSUE TITLE
Add auxiliary assets

### ISSUE THREAD

**Issue by geldmacher** [ztoben/assets-webpack-plugin#302]
**Is your feature request related to a problem? Please describe.**
You need this if, for example, a JPG image is included in a CSS file via background-image. This image file is than included in the auxiliary assets for the coresponding chunk.

**Describe the solution you'd like**
If the option includeAuxiliaryAssets is true (false by default), auxiliary assets are included. 

**Additional context**
I made this patch: https://github.com/geldmacher/assets-webpack-plugin/tree/patch-1

**Comment by ztoben** [comment]
Looks great, I'll get this merged and push out a new version.

**Comment by ztoben** [comment]
This is available in `v6.0.4`.

**Comment by geldmacher** [comment]
@ztoben My patch introduced a bug. 

See: https://github.com/geldmacher/assets-webpack-plugin/commit/ec4a20e8d031769b9fa318af08d551cfc59b1855 

Fix: https://github.com/geldmacher/assets-webpack-plugin/tree/patch-2

**Comment by ztoben** [comment]
@geldmacher fix is available in `v6.0.5`. Thanks again!
