### ISSUE TITLE
Changing webpack compiler hook from emit to afterEmit

### ISSUE THREAD

**Issue by geldmacher** [ztoben/assets-webpack-plugin#312]
**Is your feature request related to a problem? Please describe.**
It is not possible to access the emitted files in the processOutput function.

**Describe the solution you'd like**
Changing the webpack compiler hook from emit to afterEmit solves the problem.

**Comment by ztoben** [comment]
So this was originally changed during the webpack 5 upgrade because it would throw a warning for using `emit` rather than `afterEmit`, but testing it locally really quick it looks like that no longer happens so I'll get it changed back.

**Comment by ztoben** [comment]
@geldmacher should be fixed in `v6.1.0`. Thanks again!
