### ISSUE TITLE
Change Behaviour to Behavior

### ISSUE THREAD

**Issue by geldmacher** [ztoben/assets-webpack-plugin#319]
**Describe the bug**
First one is british english, second one is american english, which should be preferred i guess. My fault! ;)
This led to a bug in which no dynamic asset was recognized any more.

See: https://github.com/geldmacher/assets-webpack-plugin/commit/9858d9f74c59dfe02d57319cdc2ff662ab5433ab in https://github.com/ztoben/assets-webpack-plugin/compare/master...geldmacher:patch-4

**Comment by ztoben** [comment]
Fixed in `v6.1.2`, thanks!
