### ISSUE TITLE
Specify Webpack >=5.0.0 as peer dependency

### ISSUE THREAD

**Issue by lg-kialo** [ztoben/assets-webpack-plugin#322]
**Is your feature request related to a problem? Please describe.**
The README says that starting with version 6, the plugin only works with Webpack 5+.
But this is not reflected in the `peerDependencies` of the `package.json` so when updating my project's dependency this requirement is ignored.

**Describe the solution you'd like**
Add a `peerDependencies` section in the `package.json` specifying that the plugin works with Webpack 5+.
Like this:
```json
{
    ...
    "peerDependencies": {
        "webpack": ">=5.0.0"
    }
}
```

**Describe alternatives you've considered**
The alternative is that developers who use your package need to pay attention to the note in the README about compatibility with Webpack, I guess.

**Additional context**
No additional context.

**Comment by ztoben** [comment]
Missed this when doing the original major update to webpack 5, so I've pushed this in version `7.0.0` in case there are backward compatibility issues surfaced by the change. Thanks!
