### ISSUE TITLE
Example configuration for webpack-dev-server?

### ISSUE THREAD

**Issue by mnpenner** [ztoben/assets-webpack-plugin#35]
I've written this little PHP script for generating the HTML source code from the `webpack-assets.json` file:

``` php
function ($name) {
    static $assets;
    if($assets === null) {
        $assets = Json::loadFile(base_path('webpack-assets.json'));
    }
    if(!isset($assets[$name])) {
        throw new \Exception("Asset '$name' does not exist");
    }
    $out = [];
    foreach($assets[$name] as $kind => $path) {
        switch($kind) {
            case 'js':
                $out[] = '<script' . \Ptilz\Html::attrs(['src' => $path]) . '></script>';
                break;
            case 'css':
                $out[] = '<link' . \Ptilz\Html::attrs(['rel' => 'stylesheet', 'type' => 'text/css', 'href' => $path]) . '>';
                break;
            default:
                throw new \Exception("Unsupported asset kind: $kind");
        }
    }
    return implode("\n", $out);
}
```

Which works great with `webpack -w`, but since output doesn't contain `http://localhost:8080/...` it won't work with webpack-dev-server. I know it's possible to adjust the `publicPath` in `webpack.config.json` for this, but then it'll work for one but not the other.

Is there a way to support both `webpack` and `webpack-dev-server` with one configuration file?

**Comment by dimchez** [comment]
@mnpenner why won't it work with both `webpack` and `webpack-dev-server`?

I have `client.config.js` for `webpack` where I specify

``` js
output: {
  publicPath: '/hello/'
  ...
}
```

For `webpack-dev-server` I have `dev-server.config.js` where I specify

``` js
devServer: {
    publicPath: '/hello/',
    ...
}
```

And it seems to be working fine - assets are extracted from Webpack stats and I can use them on the server-side from JSON file.

Why would you need to have `http://localhost:8080` in the URL?

**Comment by mnpenner** [comment]
@dimchez It needs to be in the URL because the assets are served by WDS and everything else is served by nginx. They're 2 different domains.

**Comment by dimchez** [comment]
When you generate `<script>` or `<link>` tags do you know if you are running in dev mode or production? If so you could add `http://localhost:8080` on the fly. Is it possible to route to WDS through nginx like the rest of the resources? In my setup I've also had Express serving index.html and data and WDS serving static assets. Then I was simply proxying requests to WDS through Express when running in dev mode.

Anyway, this doesn't seem to be related to assets-webpack-plugin issue :)

**Comment by mnpenner** [comment]
>  do you know if you are running in dev mode or production? 

Yes, I know if I'm running in dev or production, but I don't necessarily want to use WDS in dev. I'm leaving it open whether you use WDS or `webpack -w`.

> Is it possible to route to WDS through nginx like the rest of the resources?

Hadn't considered that, but yes, I suppose that would be possible. But again, I'm not sure I'd _always_ want the requests to be forwarded to WDS.

Anyway, I just wanted to know how you envisioned handling this, I guess you're doing on the template/view side of things.

For anyone else, the best way I could figure out how to determine if WDS is running (as opposed to just dev/production) is:

``` js
var isDevServer = path.basename(require.main.filename) === 'webpack-dev-server.js';
```

And then I use that to adjust the `publicPath`. This way there's no special code in my template.
