### ISSUE TITLE
get manifest.json key inside index.html

### ISSUE THREAD

**Issue by cmnstmntmn** [ztoben/assets-webpack-plugin#43]
hey,

i'm having a static `index.html` (not generated by webpack)

inside it i would like to include one of entries declared in webpack 

```
    entry: {
        admin: './assets/admin/index.js',
        app: './assets/app/index.js',
        vendor: ['jquery', 'd3']
    }
```

the `manifest.json` is generated, but i have no ideea how i could parse html on each build and push targeted entry.

any ideea about what plugin could parse `index.html` and write out from `manifest.json` ?

**Comment by huangshuwei** [comment]
@cmnstmntmn 
hi,I find this issues.There was no need to use this plugin.
You can refer to this plugin(work well):
https://www.npmjs.com/package/html-webpack-plugin
