### ISSUE TITLE
Does it work with chunked CSS?

### ISSUE THREAD

**Issue by mech** [ztoben/assets-webpack-plugin#5]
I have single chunked CSS + JS, but it appear to only can output once.

```
{"builder":"/css/builder-ff7029d929fbad65d968.css"}
```

The JS somehow is missing like `/js/builder-ff7029d929fbad65d968.js`

**Comment by sporto** [comment]
Hi, there has been several changes in v2. Not sure if this is still valid, could you check with v2?

**Comment by ztoben** [comment]
This should be working with the current version, let me know if not. Thanks.
