### ISSUE TITLE
No assets in manifest with `copy-webpack-plugin`

### ISSUE THREAD

**Issue by alexander-akait** [ztoben/assets-webpack-plugin#51]
If i use `copy-webpack-plugin` 

``` js
new CopyWebpackPlugin([
                {
                    from: DEBUG
                        ? path.join(process.cwd(), 'node_modules/jquery/dist/jquery.js')
                        : path.join(process.cwd(), 'node_modules/jquery/dist/jquery.min.js'),
                    to: 'jquery/jquery.js' // use 'jquery/jquery.[hash].js' also not working
                }
]);
```

I do not have `jquery` in the assets manifest, is there something you can solve it or a bug?

**Comment by roastlechon** [comment]
I have this problem too

**Comment by roastlechon** [comment]
I am using `copy-webpack-plugin-hash` version, which outputs a hash with file. However, `assets-webpack-plugin` does not list it out

**Comment by alexander-akait** [comment]
@roastlechon it is not convenient because there is no manifest file and might not know which hash now has file

**Comment by kartiklad** [comment]
I have a similar issue but with `extract-text-plugin`. I use the plugin make a css file which isn't imported in any of the entry points. The `assets-webpack-plugin` does not list it out :/

**Comment by wootencl** [comment]
@evilebottnawi Were you ever able to work around this?

**Comment by alexander-akait** [comment]
@wootencl no

**Comment by ztoben** [comment]
Is this still happening with the latest version? (`3.7.1`)

**Comment by wootencl** [comment]
@ztoben It seems to be resolved 🎉. Two things I noticed though:
- `prettyPrint` doesn't seem to work with the `processOutput` options. Not a huge deal but could maybe make a note in the README.
- Non chunk assets are lumped into an empty string key of the assets object like so:
```
{
  ..., //chunks,
 "": {
    "svg": [...],
    "png: [...],
    "js": [...]
  }
}
```
Not sure if that's intended functionality. 

As far as this issue goes though I'd say you're safe to close (at least from my perspective).

**Comment by ztoben** [comment]
Mind opening issues for both things you mentioned? Closing this one.
