### ISSUE TITLE
No manifest.text when using Webpack v2.1-beta25

### ISSUE THREAD

**Issue by wmertens** [ztoben/assets-webpack-plugin#53]
Apologies, I haven't dug into this very deeply, but it seems that when using WP 2.1, using `includeManifest: true` does not actually add the text…

**Comment by Vani-gurnani** [comment]
+1 Faced same issue

**Comment by Vani-gurnani** [comment]
@wmertens did you found the workaround of this ?

**Comment by mm-au** [comment]
Instead of doing `includeManifest: true` you need to pass the name of the manifest chunk:
```
includeManifest: 'manifest'
```

It's also worth noting it doesn't currently work when you have sourcemaps but there is PR #56 to fix that.

**Comment by maxmilton** [comment]
Instead of doing `includeManifest: true` you need to pass the name of the manifest chunk:
```
includeManifest: 'manifest'
```

It's also worth noting it doesn't currently work when you have sourcemaps but there is PR #56 to fix that.

**Comment by ztoben** [comment]
This was fixed in `3.5.1`.
