### ISSUE TITLE
Incompatible with inline source maps

### ISSUE THREAD

**Issue by braska** [ztoben/assets-webpack-plugin#57]
If I use inline source maps I get error: `Could not locate manifest function in source`.

Error occurs in `node_modules/assets-webpack-plugin/index.js`
This occurs because `compilation.assets[manifestAssetKey]` contains `children` field (array) instead of `_value` field while inline source map used.

**Comment by dekked** [comment]
Fixed in https://github.com/kossnocorp/assets-webpack-plugin/pull/56 ?
