### ISSUE TITLE
Support multiple asset types per chunk

### ISSUE THREAD

**Issue by kostasmanionis** [ztoben/assets-webpack-plugin#60]
Hello!

Seems like this only supports one asset type per chunk. Stuff breaks when I have multiple css per chunk. For e.g.

```
index.css
index.above.css
```

It outputs something like this

```
  "index": {
    "js": "/mobile/public/dist/index.eae6d77f.js",
    "css": "/mobile/public/dist/index.3dcf8c31.above.css"
  },
```

I could send in a PR if we could agree on how to handle these cases.

**Comment by ztoben** [comment]
Fixed in release `3.6.3`.
