### ISSUE TITLE
Sort order of JSON assets

### ISSUE THREAD

**Issue by stephen-last** [ztoben/assets-webpack-plugin#66]
I'm using React server rendering to generate the HTML for a website. I'm trying to use `assets-webpack-plugin` so I can generate the script tags for the webpack asset bundles.

I am generating a `manifest.js` file using the `CommonsChunkPlugin()` plugin.

At the moment, the resulting JSON assets file puts the `manifest.js` bundle last, like this:

```json
{
  "bundle": {
    "js": "js/bundle.js",
    "css": "css/bundle.css"
  },
  "vendor": {
    "js": "js/vendor.js"
  },
  "manifest": {
    "js": "js/manifest.js"
  }
}
```

I have a function to generate the HTML tags, it takes the `assets` from the JSON file (and uses `lodash/map`):

```js
function assetTags (assets, type) {
  const tags = map(assets, (asset, index) => {
    return <script key={index} src={asset[type]} />
  })
  return tags
}
```

This produces:

```html
<script src="js/bundle.js"></script>
<script src="js/vendor.js"></script>
<script src="js/manifest.js"></script>
```

I need the manifest to be first to avoid errors. 

I know I can update my `assetTags()` function to do this manually, but it would be nice to have an option for sorting the bundles in the output JSON file. Or, an option like `manifestFirst: true` because it's always going to need to be added first in the HTML.

**Comment by abou7mied** [comment]
+1
My config is
```js
module.exports = {
  entry: {
    vendor: [
      ...
    ],
    app: [
      ...
    ]
  }
}
```
and assets.json
```json
{
  "app": {
    "js": "/assets/app.js"
  },
  "vendor": {
    "js": "/assets/vendor.js"
  }
}
```
but If i interated on the json output I would get wrong order
```html
<script src="assets/app.js"></script>
<script src="assets/vendor.js"></script>
```

Webpack inject bootstrap code into vendor and it should be loaded before app.js

**Comment by moimael** [comment]
Yes a manifestFirst option would be awesome !

**Comment by Redmega** [comment]
Javascript object properties have no set order. Maps will go through them in arbitrary order, sometimes in the order they were inserted and sometimes in a random order.

**Comment by ztoben** [comment]
As @Redmega mentioned, I'm not sure there is a way to sort object properties. Feel free to submit a PR if you find out a way to, I'd be happy to review it.

**Comment by lo1tuma** [comment]
So the solution would be to use an array, which has an order.

For example:

```json
[
  {
    "name": "manifest",
    "files": {
      "js": "js/manifest.js"
    }
  },
   {
    "name": "vendor",
    "files": {
      "js": "js/vendor.js"
    }
  },
  {
    "name": "bundle",
    "files": {
      "js": "js/bundle.js",
      "css": "css/bundle.css"
    }
  }
]
```

**Comment by ztoben** [comment]
Doesn't really seem like the responsibility of this package to do the sorting. I could add an option to wrap output in an array though if that's something people want.

**Comment by ztoben** [comment]
After a little review I think this can be done with something like this: 

```js
function orderManifest(manifest) {
    return Object.assign({}, ...Object.keys(manifest).map(i => ({[i]: manifest[i]})).sort((a, b) => {
  	if (a.manifest) {
    	return -1;
    }
    
    if (b.manifest) {
    	return 1;
    }
    
    return 0;
  }));
}
```

Working example via jsFiddle [here](https://jsfiddle.net/hv2Lk5g9/26/).

**Comment by ztoben** [comment]
This is added in release `3.8.1` with the `manifestFirst` option.
