### ISSUE TITLE
Webpack 2, fullPath option having no effect

### ISSUE THREAD

**Issue by jewbetcha** [ztoben/assets-webpack-plugin#68]
I'm having trouble getting the `fullPath` option to work with my config. The JSON is generated just fine, but when adding `fullPath: false` there is no difference in the generated file. File paths are still the full length.

Here's what my config looks like:
```
new AssetsPlugin({
    filename: 'assets.json',
    fullPath: false
})
```
Does this plugin work with webpack 2? Thanks :)

**Comment by githubdoramon** [comment]
Same here

**Comment by ztoben** [comment]
This one is strange. If you delete your assets.json file and then re-run the webpack build, doesn't it write it correctly? That's how it seems to behave for me.
