### ISSUE TITLE
splitted files not found when used with AggressiveSplittingPlugin

### ISSUE THREAD

**Issue by jetfontanilla** [ztoben/assets-webpack-plugin#70]
using this configuration:
```js
new AssetsPlugin({
                filename: "assets." + lang + ".json",
                fullPath: false
            }),
```

produces the correct output for the entry look-up

however, once AggressiveSplittingPlugin is added:
```js
new AssetsPlugin({
                filename: "assets." + lang + ".json",
                fullPath: false
            }),
new webpack.optimize.AggressiveSplittingPlugin({
                minSize: 30000,
                maxSize: 50000
            }),
```

produces the incorrect output.

expected:
- output file should show the list of chunks or entry chunk for the splitted files

findings:
- very small entry bundles not affected by the splitting plug-in would still show up in the output file
- large bundles that have been splitted into smaller chunks do not show up

Env:
node v8.0.0
assets-webpack-plugin: 3.5.1
webpack: 3.0.0-rc.0

**Comment by ztoben** [comment]
Can you still replicate this with the latest version? I believe it should be fixed now.
