### ISSUE TITLE
Webpack 2 path to files without slash

### ISSUE THREAD

**Issue by eseQ** [ztoben/assets-webpack-plugin#71]
in webpack v 1 all was fine, but in v2 generate json without slash 
```javascript
new AssetsPlugin({
  prettyPrint: true,
  path: "../public/",
}),
```
slash is missing:
```
"main": {
  "js": "/webpackmain.0d202c04838160cdbeed.js",
  "css": "/webpackcss/main-7852e8fe6c98d01cc98d.css"
}
```

**Comment by eseQ** [comment]
UPD:
that was because i use path.resolve in output, in webpack 1 I use relative path

**Comment by ztoben** [comment]
If this is still relevant, would you mind testing with the latest version `3.7.1` and letting me know if it's an issue still? Seems the same as #88, which should be fixed.
