### ISSUE TITLE
miss some css file manifest

### ISSUE THREAD

**Issue by lerit** [ztoben/assets-webpack-plugin#72]
i have two entry,one for app another for vendor,i debug you code :
**stats.assetsByChunkName** is:
`{ apps:
   [ 'apps.bundle.js',
     'apps.bundle.css',
     'apps.bundle.scss.css',
     'apps.bundle.js.map',
     'apps.bundle.css.map',
     'apps.bundle.scss.css.map' ],
  vendors:
   [ 'vendors.bundle.js',
     'vendors.bundle.css',
     'vendors.bundle.scss.css',
     'vendors.bundle.js.map',
     'vendors.bundle.css.map',
     'vendors.bundle.scss.css.map' ] }`
 **output** is:
`{ apps:
   { js: 'http://localhost:4001/dist/apps.bundle.js',
     css: 'http://localhost:4001/dist/apps.bundle.scss.css' },
  vendors:
   { js: 'http://localhost:4001/dist/vendors.bundle.js',
     css: 'http://localhost:4001/dist/vendors.bundle.scss.css' } }`
it miss file endswith 'scss.css'
i use two '**extract-text-webpack-plugin**' one for css and another for scss,so one entry has two css file.
my webpack setting:
{
entry:{
vendors:xxx
apps:xxxx
}
..
plugins:[
 new ExtractTextPlugin({
  filename:'[name].bundle.css'
}),
new ExtractTextPlugin({
  filename:'[name].bundle.scss.css'
})
]
}

**Comment by samuelmaddock** [comment]
It looks like the assets plugin only supports one file per-extension, per-chunk. As a workaround, you can change the extension name of your second `ExtractTextPlugin` instance.
```diff
new ExtractTextPlugin({
-   filename:'[name].bundle.scss.css'
+   filename:'[name].bundle.scss'
})
```
Now the resulting output should appear as
```json
{
   "apps": {
      "js": "http: //localhost:4001/dist/apps.bundle.js",
      "css": "http://localhost:4001/dist/apps.bundle.css",
      "scss": "http://localhost:4001/dist/apps.bundle.scss"
   },
   "vendors": {
      "js": "http://localhost:4001/dist/vendors.bundle.js",
      "css": "http://localhost:4001/dist/vendors.bundle.css",
      "scss": "http://localhost:4001/dist/vendors.bundle.scss"
   }
}
```
Even though the filename has a different extension, it _should_ still load fine. Of course, if you have any server rules filtering for `.css`, you'll have to keep that in mind.

#64 contains an actual fix

**Comment by lerit** [comment]
thanks

**Comment by ztoben** [comment]
Fixed in https://github.com/kossnocorp/assets-webpack-plugin/commit/95d802adfc0c839872d0ba4c689ccd1de41c5918.
