### ISSUE TITLE
processOutput in combination with Watch Mode leads to nested data

### ISSUE THREAD

**Issue by PascalPflaum** [ztoben/assets-webpack-plugin#73]
When using
"watch: true" and "keepalive: true"

process output leads to strange effects.
```javascript
new AssetsPlugin({
                filename: './config/assets.json',
                processOutput: (assets) => JSON.stringify({assets}),
                prettyPrint: true,
            }),
```

It looks like processOutputs somehow manipulates something stateful. After each run the config gets nested another level.

```javascript
{
  "assets": {
    "assets": {
      "assets": {
        "admin": {
          "js": "admin.js",
          "css": "admin.css"
        },
        "main": {
          "js": "main.js",
          "css": "main.css"
        }
      },
      "admin": {
        "js": "admin.js",
        "css": "admin.css"
      },
      "main": {
        "js": "main.js",
        "css": "main.css"
      }
    },
    "admin": {
      "js": "admin.js",
      "css": "admin.css"
    },
    "main": {
      "js": "main.js",
      "css": "main.css"
    }
  }
}
```

**Comment by PascalPflaum** [comment]
I found the issue at 
[createOutputWriter.js#L36](https://github.com/kossnocorp/assets-webpack-plugin/blob/9f9407bdb887be7a8a9e17bce632b18f8fa6d51f/lib/output/createOutputWriter.js#L36)

I suggest to make the parsing of the existing data overloadable as well.
If you agree on this, I would make this change and create a pull request.

**Comment by PascalPflaum** [comment]
If somebody else runs into the same problem, here my workaround using npm packages deep-merge and lodash/omit

```javascript
new AssetsPlugin({
                filename: './config/assets.json',
                processOutput: (assets) => {
                    assets = deepMerge(assets.assets || {}, omit(assets, 'assets'));
                    return JSON.stringify({assets});
                },
            }),
```

**Comment by ztoben** [comment]
Would be happy to review a pr if you submit one for this issue.

**Comment by ztoben** [comment]
I can't seem to duplicate this with the setup you've listed. It always just creates the assets level object once. Here's what my output looks like, after multiple runs: 

```js
{
   "assets": {
      "main": {
         "js": "/bundle.js"
      },
      "": {
         "pdf": "/public/resume.pdf",
         "jpg": "/72ed0ed4aa5b7afc46dcefc892456b10.jpg",
         "gz": "/bundle.js.gz"
      }
   }
}
```

**EDIT**: Nevermind, I will reopen. I can duplicate this now.

**Comment by ztoben** [comment]
Ah, okay nevermind. I see the issue now. You're nesting it another layer deep in assets every time it's run, this is definitely expected behavior for how you have it configured. I'm not sure that anything different would be expected here. You're asking keep-alive to save all of your assets from last time, and then saving them in an object with the key `assets`, so it'll just keep nesting forever.
