### ISSUE TITLE
Unsure of the reason for using non capturing group with HASH_PLACEHOLDER_REGEX

### ISSUE THREAD

**Issue by vamsiampolu** [ztoben/assets-webpack-plugin#75]
The regex for `HASH_PLACEHOLDER_REGEX` has a part that looks like this:

```
((?:chunk)?hash)
```

However, when I tested it in regexplanet, it seems to match the whole `chunkhash` into the first group. 

<img width="1435" alt="screenshot 2017-08-01 06 39 25" src="https://user-images.githubusercontent.com/3782648/28797530-039b8808-7685-11e7-8680-a22d28009d5e.png">

What is the intention behind creating a seperate non capturing group for chunk when it gets captured anyways?

**Comment by ztoben** [comment]
Is this breaking some functionality? Or just because you're curious?
