### ISSUE TITLE
The plugin has been outdated due to upgrade of webpack.

### ISSUE THREAD

**Issue by lcxfs1991** [ztoben/assets-webpack-plugin#83]
Hi @kossnocorp @sporto 
I am wondering whether this project is still under maintenance because when I run test, I find a few failure.

In addition, the dependency is outdated.

Looking forward to your reply.

**Comment by lcxfs1991** [comment]
Any update here?

**Comment by ztoben** [comment]
Should be working fine on the latest version of webpack now.
