### ISSUE TITLE
Incorrect assets-catalog.json in webpack 4 during Hot Update

### ISSUE THREAD

**Issue by StalkAlex** [ztoben/assets-webpack-plugin#85]
![webpack](https://user-images.githubusercontent.com/2943154/37151451-59212408-22f7-11e8-80aa-3253a2f429d3.JPG)
![assets](https://user-images.githubusercontent.com/2943154/37151453-5a2e7cc4-22f7-11e8-8609-208b513d18f7.JPG)

Here can be seen that hot update chunk was added like whole asset bundle to catalog and it make page that uses this bundle unworkable.

There wasn't such problem in Webpack 3.

**Comment by jsantha** [comment]
Default webpack hot update file name pattern is: **[id].[hash].hot-update.js** where assets plugin expecting the [id] to be numeric only. Your pattern is **notifications**.[hash].hot-update.js

Temporary workaround seems to be omitting the **[id]** part at webpack's output.hotUpdateChunkFilename.

`output: {
hotUpdateChunkFilename: '[hash].hot-update.js'
}`

**Comment by StalkAlex** [comment]
Thank you, it's working now again. Should I close an issue?

**Comment by smoakey** [comment]
@JSantha Thank you!

**Comment by dlebedynskyi** [comment]
is there a chance for this to get fixed in plugin?

**Comment by ztoben** [comment]
Should be fixed by #89 when/if it gets merged.

**Comment by kossnocorp** [comment]
Fix for the problem was published with `assets-webpack-plugin@3.6.0`.
