### ISSUE TITLE
Webpack 4 deprecation warning

### ISSUE THREAD

**Issue by Aeonrush** [ztoben/assets-webpack-plugin#86]
Hi
I have this warning
```
(node:3792) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```
Modules
```
"assets-webpack-plugin": "^3.5.1",
"webpack": "^4.1.1",
```
Thank you

**Comment by miusuncle** [comment]
I encounter the same problem

**Comment by wellyshen** [comment]
Hi I have the same issue.

**Comment by rouwe111** [comment]
Same problem here, but there isn't a lot of activity in this repo :( Found another project which looks promising: https://github.com/webdeveric/webpack-assets-manifest

**Comment by stephen-last** [comment]
I'm seeing this too, on version `3.5.1`.

> DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

> at AssetsWebpackPlugin.apply (C:\...\node_modules\assets-webpack-plugin\index.js:28:14)

Needs updating for use with webpack 4.

**Comment by jimblue** [comment]
Hey @kossnocorp !

Just wondering if upgrading this library to webpack 4 is in you mind?
We need to know if we should use another library or just wait a bit.

Thank you!!

Cheers

**Comment by stoikerty** [comment]
@ztoben did some work to get the plugin webpack-4 ready in this PR:
https://github.com/kossnocorp/assets-webpack-plugin/pull/89

An update on this issue would be welcome, @kossnocorp looks like this could be an easy win if you have a bit of time to look over his PR.
