### ISSUE TITLE
list .gz files

### ISSUE THREAD

**Issue by themojilla** [ztoben/assets-webpack-plugin#87]
Hi and thanx for this great repo
I wanna use CompressionPlugin for prod webpack config along with assets-webpack
The problem is the webpack-assets.json is only included js files not .gz files 

how can achieve that?

`

    plugins: [
        ...Base.plugins,
        new AssetsPlugin({
            path: path.resolve('./dist'),
            filename: 'assets.json',
            prettyPrint: true,
        }),
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: '"production"'
            },
            __CLIENT__: true,
            __SERVER__: false,
            __DEV__: false,
        }),
         new CompressionPlugin({
             asset: '[path].gz[query]',
             algorithm: 'gzip',
             test: /\.jsx?$|\.css$|\.(scss|sass)$|\.html$/,
             threshold: 8192,
             minRatio: 0.8,
             deleteOriginalAssets: true
         }),
    ]

`

**Comment by ztoben** [comment]
This should be fixed with #65, and available in version `3.7.0`. Let me know if there are still issues.

Edit: Just tested locally with the latest version and gz files are included in the manifest.
