### ISSUE TITLE
Not creating assets json running webpack dev server after 3.6.1

### ISSUE THREAD

**Issue by StalkAlex** [ztoben/assets-webpack-plugin#93]
Have to make some changes in config after update from 3.6.0,  but running through webpack is working fine now(production build), it creates json with assets, but using webpack dev server is not updating generated assets json file. Hot to fix this and return to an old behavior?

**Comment by SlyDeath** [comment]
I have the same problem

**Comment by StalkAlex** [comment]
Temporary workaround is to define `processOutput` func in plugin's config and write to file there, but it's a kludge.

**Comment by ztoben** [comment]
Yeah, considering just reverting the #90 as it seems to have broken it.

**Comment by ztoben** [comment]
Could you try `3.8.0` and see if you have the same problem?

**Comment by StalkAlex** [comment]
Yeap, it's been fixed. Thanks!
