### ISSUE TITLE
Update tags in github

### ISSUE THREAD

**Issue by stoikerty** [ztoben/assets-webpack-plugin#94]
This isn't an issue with the package itself not a big issue either.
I just wanted to remind that the tags are missing in github for the latest versions.

I installed `3.8.3` even though the latest tagged release on github is only `3.7.1`

**Comment by ztoben** [comment]
Yeah, I don't always remember to do it. I'll try configuring the `.travis.yml` to do it for me.

**Comment by stoikerty** [comment]
Nice! I see you've already changed the travis file. I'll close this issue then.
Thanks!
